# mytempbasis <- create.fourier.basis(c(0,365), 9)
# mytempSmooth <- smooth.basis(day.5,daily$tempav,mytempbasis)
# plotfit.fd(daily$tempav,day.5,mytempSmooth$fd)

library(fda)
library(fda.usc)
data(CanadianWeather)
tempdat <- t(daily$tempav)
tempdat.fdata <- fdata(tempdat,argvals=(1:365)-0.5,rangeval=range(0.5:364.5),names=list(main="Yearly observations of temperatures",xlab="Days",ylab="Temperatures"))
temp.svd <- fdata2pc(tempdat.fdata, ncomp=4)
norm.fdata(temp.svd$rotation[1:2])
plot(temp.svd$rotation,main="3 Functional PC",lwd=2)
#required(graphics.off)
summary(temp.svd, biplot=FALSE)
plot(weeks,temp.svd$rotation[1])


unitvec <- seq(from=0,to=1,length.out=100)
t.bs <- bs(unitvec,degree=3,df=4,intercept=T)
plot(c(0,1),c(0,1),type="n",main="B-Splines Basis",xlab="x",ylab="")
mtext(expression(B[j3](x)),side=2, line=2.5)
lines(unitvec,t.bs[,1],lwd=1,lty=2,col=2)
lines(unitvec,t.bs[,2],lwd=1,lty=2,col=3)
lines(unitvec,t.bs[,3],lwd=1,lty=2,col=4)
lines(unitvec,t.bs[,4],lwd=1,lty=2,col="black")
lines(unitvec,t.bs[,5],lwd=1,lty=2,col="goldenrod4")